apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: ${PROJECT_NAME}
servers: 1
image: rancher/k3s:v1.28.1-k3s1
hostAliases:
  - hostnames:
      - ${GITEA_URL}
    # Replace with the IP of the machine where Gitea is running
    ip: <GITEA_IP>
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:* 
