apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: ${PROJECT_NAME}
servers: 1
image: rancher/k3s:latest
hostAliases:
  - hostnames:
      - ${GIT_SERVER}
    ip: ${GIT_SERVER_IP}
ports:
  - port: 80:80
  - port: 443:443
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:* 
