output:
  sort-results: true
  print-issued-lines: false

linters:
  disable-all: true
  enable:
    # golangci-lint defaults:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters:
    - nolintlint
    - bodyclose
    - dupl
    - errname
    - forbidigo
    - gocritic
    - godox
    - gofumpt
    - goimports
    - err113
    - ireturn
    - misspell
    - musttag
    - nakedret
    - revive
    - thelper

linters-settings:
  forbidigo:
    forbid:
      - 'ioutil\.*'
  gocritic:
    enabled-checks:
      - sloppyReassign
    settings:
      captLocal:
        paramsOnly: false
