apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca-certificate
  namespace: cert-manager
spec:
  isCA: true
  commonName: "*" # Wildcard certificate
  secretName: root-ca-certificate
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
